# Generated by Django 2.2.6 on 2023-04-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20230412_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
